In [1]:
import numpy as np
from numpy.linalg import norm

In [2]:
a = np.array([4, 2, 4])
b = np.array([12, 3, 4])

In [3]:
print(f'l1 норма вектора a: {norm(a, ord=1)}')
print(f'l1 норма вектора b: {norm(b, ord=1)}')

l1 норма вектора a: 10.0
l1 норма вектора b: 19.0


In [4]:
print(f'l2 норма вектора a: {norm(a, ord=2)}')
print(f'l2 норма вектора b: {norm(b, ord=2)}')

l2 норма вектора a: 6.0
l2 норма вектора b: 13.0


In [5]:
cos_phi = np.dot(a, b) / norm(a) / norm(b)
print(f'Косинус угла между a и b: {cos_phi:.3f}')
print(f'Угол между a и b: {np.arccos(cos_phi):.3f}')

Косинус угла между a и b: 0.897
Угол между a и b: 0.457


In [6]:
def orthonorm_basis(a, b, c):
    if a @ b != 0:
        print('Не образуют ортонормированный базис. т.к: (a @ b != 0)')
    elif a @ c != 0:
        print('Не образуют ортонормированный базис. т.к: (a @ c != 0)')
    elif b @ c != 0:
        print('Не образуют ортонормированный базис. т.к: (b @ c != 0)')
    elif round(a @ a, 3) != 1:
        print('Не образуют ортонормированный базис. т.к: (a @ a != 1)')
    elif round(b @ b, 3) != 1:
        print('Не образуют ортонормированный базис. т.к: (b @ b != 1)')
    elif round(c @ c, 3) != 1:
        print('Не образуют ортонормированный базис. т.к: (c @ c != 1)')
    else:
        print('Образуют ортонормированный базис!!!')
        

In [7]:
a = np.array([1/np.sqrt(2), -1/np.sqrt(2), 0])
b = np.array([1/np.sqrt(2), 1/np.sqrt(2), 0])
c = np.array([0, 0, 1])
a, b, c

(array([ 0.70710678, -0.70710678,  0.        ]),
 array([0.70710678, 0.70710678, 0.        ]),
 array([0, 0, 1]))

In [8]:
orthonorm_basis(a, b, c)

Образуют ортонормированный базис!!!


In [9]:
a = np.array([1/2, -1/2, 0])
b = np.array([0, 1/2, 1/2])
c = np.array([0, 0, 1])
a, b, c

(array([ 0.5, -0.5,  0. ]), array([0. , 0.5, 0.5]), array([0, 0, 1]))

In [10]:
orthonorm_basis(a, b, c)

Не образуют ортонормированный базис. т.к: (a @ b != 0)


In [11]:
a = np.array([1, 0, 0])
b = np.array([0, 1, 0])
c = np.array([0, 0, 1])
a, b, c

(array([1, 0, 0]), array([0, 1, 0]), array([0, 0, 1]))

In [12]:
orthonorm_basis(a, b, c)

Образуют ортонормированный базис!!!
